### ISSUE TITLE
Urgent 

### ISSUE THREAD

**Issue by Maryam19f19276** [Maryam19f19276/SQA19f19276#3]
Ther is an error in the codes (line No.20)

**Comment by bashayer19f19326** [comment]
I made a modification to the code on line 20 and let me know if is any problem.

**Comment by Maryam19f19276** [comment]
I noticed the difference and the change in the codes. 
If you encounter any programming problem, you can come back again.

**Comment by bashayer19f19326** [comment]
Thanks for all your feedback and if I find any errors I will get back to you.
